-- ============================================================
-- Classroom Booking System — Oracle XE Setup Script
-- System Setup & Clean Initialization
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- 1. DROP EXISTING TABLES (Reverse dependency order)
-- ────────────────────────────────────────────────────────────
DROP TABLE Booking_Audit CASCADE CONSTRAINTS PURGE;
DROP TABLE Notifications CASCADE CONSTRAINTS PURGE;
DROP TABLE Cancellations CASCADE CONSTRAINTS PURGE;
DROP TABLE PeriodicDetails CASCADE CONSTRAINTS PURGE;
DROP TABLE Enrollments CASCADE CONSTRAINTS PURGE;
DROP TABLE Bookings CASCADE CONSTRAINTS PURGE;
DROP TABLE Classrooms CASCADE CONSTRAINTS PURGE;
DROP TABLE Courses CASCADE CONSTRAINTS PURGE;
DROP TABLE Users CASCADE CONSTRAINTS PURGE;
DROP TABLE Departments CASCADE CONSTRAINTS PURGE;
DROP TABLE Semesters CASCADE CONSTRAINTS PURGE;
DROP TABLE Roles CASCADE CONSTRAINTS PURGE;
DROP TABLE BookingTypes CASCADE CONSTRAINTS PURGE;
DROP TABLE BookingStatuses CASCADE CONSTRAINTS PURGE;
DROP TABLE NotifTypes CASCADE CONSTRAINTS PURGE;
DROP TABLE DaysOfWeek CASCADE CONSTRAINTS PURGE;

-- ────────────────────────────────────────────────────────────
-- 2. LOOKUP / REFERENCE TABLES
-- ────────────────────────────────────────────────────────────
CREATE TABLE Roles (
    role_id   NUMBER PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL
);

CREATE TABLE BookingStatuses (
    status_id   NUMBER PRIMARY KEY,
    status_name VARCHAR2(50) NOT NULL
);

CREATE TABLE BookingTypes (
    type_id   NUMBER PRIMARY KEY,
    type_name VARCHAR2(50) NOT NULL
);

CREATE TABLE DaysOfWeek (
    day_id   NUMBER PRIMARY KEY,
    day_name VARCHAR2(10) NOT NULL
);

CREATE TABLE NotifTypes (
    notif_type_id NUMBER PRIMARY KEY,
    type_name     VARCHAR2(50) NOT NULL
);

CREATE TABLE Semesters (
    semester_id NUMBER PRIMARY KEY,
    name        VARCHAR2(50),
    start_date  DATE,
    end_date    DATE
);

-- ────────────────────────────────────────────────────────────
-- 3. CORE DOMAIN TABLES
-- ────────────────────────────────────────────────────────────
CREATE TABLE Departments (
    dept_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR2(100)
);

CREATE TABLE Users (
    user_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR2(100) NOT NULL,
    email      VARCHAR2(100) UNIQUE NOT NULL,
    role_id    NUMBER REFERENCES Roles(role_id),
    phone      VARCHAR2(15),
    password   VARCHAR2(100) NOT NULL,
    role       VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Classrooms (
    room_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building      VARCHAR2(50),
    room_number   VARCHAR2(10) NOT NULL,
    capacity      NUMBER CHECK (capacity > 0),
    has_projector NUMBER(1) DEFAULT 0,
    has_ac        NUMBER(1) DEFAULT 0
);

CREATE TABLE Courses (
    course_id VARCHAR2(20) PRIMARY KEY,
    title     VARCHAR2(100) NOT NULL,
    dept_id   NUMBER REFERENCES Departments(dept_id),
    credits   NUMBER CHECK (credits > 0)
);

CREATE TABLE Bookings (
    booking_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    faculty_id      NUMBER NOT NULL REFERENCES Users(user_id),
    room_id         NUMBER NOT NULL REFERENCES Classrooms(room_id),
    course_id       VARCHAR2(20) REFERENCES Courses(course_id),
    booking_type_id NUMBER REFERENCES BookingTypes(type_id),
    booking_date    DATE NOT NULL,
    start_time      DATE NOT NULL,
    end_time        DATE NOT NULL,
    semester_id     NUMBER REFERENCES Semesters(semester_id),
    status_id       NUMBER DEFAULT 1 REFERENCES BookingStatuses(status_id),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_times CHECK (end_time > start_time)
);

CREATE TABLE PeriodicDetails (
    periodic_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  NUMBER NOT NULL REFERENCES Bookings(booking_id) ON DELETE CASCADE,
    day_id      NUMBER NOT NULL REFERENCES DaysOfWeek(day_id),
    end_date    DATE NOT NULL
);

CREATE TABLE Enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id    NUMBER NOT NULL REFERENCES Users(user_id),
    course_id     VARCHAR2(20) NOT NULL REFERENCES Courses(course_id),
    semester_id   NUMBER REFERENCES Semesters(semester_id),
    CONSTRAINT uq_enrollment UNIQUE (student_id, course_id, semester_id)
);

CREATE TABLE Cancellations (
    cancel_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id     NUMBER NOT NULL REFERENCES Bookings(booking_id),
    cancelled_by   NUMBER,
    cancelled_date DATE DEFAULT SYSDATE,
    reason         VARCHAR2(200)
);

CREATE TABLE Notifications (
    notif_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       NUMBER NOT NULL,
    message       VARCHAR2(200) NOT NULL,
    notif_type_id NUMBER REFERENCES NotifTypes(notif_type_id),
    is_read       NUMBER(1) DEFAULT 0,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Booking_Audit (
    audit_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER,
    action     VARCHAR2(20),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ────────────────────────────────────────────────────────────
-- 4. VIEWS
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW BookingDetails AS
SELECT
    b.booking_id,
    u.name,
    c.room_number,
    b.booking_date,
    b.start_time,
    b.end_time,
    s.status_name
FROM Bookings b
JOIN Users u ON b.faculty_id = u.user_id
JOIN Classrooms c ON b.room_id = c.room_id
JOIN BookingStatuses s ON b.status_id = s.status_id
WHERE b.status_id != 3;

CREATE OR REPLACE VIEW RoomUsage AS
SELECT
    room_id,
    COUNT(*) AS total_bookings
FROM Bookings
GROUP BY room_id;

CREATE OR REPLACE VIEW Dept_Capacity_Report AS
SELECT 
    NVL(d.name, 'All Departments') AS department,
    NVL(c.building, 'All Buildings') AS building,
    SUM(c.capacity) AS total_seat_capacity,
    COUNT(c.room_id) AS total_rooms
FROM Classrooms c
LEFT JOIN Bookings b ON c.room_id = b.room_id
LEFT JOIN Courses cr ON b.course_id = cr.course_id
LEFT JOIN Departments d ON cr.dept_id = d.dept_id
GROUP BY ROLLUP(d.name, c.building);

-- ────────────────────────────────────────────────────────────
-- 5. TRIGGERS
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE TRIGGER prevent_overlap
BEFORE INSERT ON Bookings
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM Bookings
    WHERE room_id      = :NEW.room_id
      AND booking_date = :NEW.booking_date
      AND status_id   != 3
      AND start_time   < :NEW.end_time
      AND end_time     > :NEW.start_time;

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Room already booked for that time slot.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER faculty_schedule_conflict
BEFORE INSERT ON Bookings
FOR EACH ROW
DECLARE
    v_faculty_conflict NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_faculty_conflict
    FROM Bookings
    WHERE faculty_id   = :NEW.faculty_id
      AND booking_date = :NEW.booking_date
      AND status_id   != 3
      AND start_time   < :NEW.end_time
      AND end_time     > :NEW.start_time;

    IF v_faculty_conflict > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Faculty schedule conflict: You are already teaching in another room during this exact time slot.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER notify_on_booking
AFTER INSERT ON Bookings
FOR EACH ROW
BEGIN
    -- Notify the Faculty who booked it
    INSERT INTO Notifications (user_id, message, is_read)
    VALUES (:NEW.faculty_id, 'Booking Confirmed for course ' || NVL(:NEW.course_id, 'General') || ' in room ' || :NEW.room_id, 0);
    
    -- Broadcast to all Enrolled Students
    IF :NEW.course_id IS NOT NULL THEN
        FOR student_rec IN (SELECT student_id FROM Enrollments WHERE course_id = :NEW.course_id) LOOP
            INSERT INTO Notifications (user_id, message, is_read)
            VALUES (student_rec.student_id, 'New class scheduled: ' || :NEW.course_id || ' in room ' || :NEW.room_id || ' (' || TO_CHAR(:NEW.booking_date, 'Mon DD') || ')', 0);
        END LOOP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER notify_cancel
AFTER UPDATE ON Bookings
FOR EACH ROW
WHEN (NEW.status_id = 3 AND OLD.status_id != 3)
BEGIN
    -- Notify the Faculty
    INSERT INTO Notifications (user_id, message, is_read)
    VALUES (:NEW.faculty_id, 'Your booking for room ' || :NEW.room_id || ' has been cancelled.', 0);
    
    -- Broadcast Cancellation to Enrolled Students
    IF :NEW.course_id IS NOT NULL THEN
        FOR student_rec IN (SELECT student_id FROM Enrollments WHERE course_id = :NEW.course_id) LOOP
            INSERT INTO Notifications (user_id, message, is_read)
            VALUES (student_rec.student_id, 'ALERT: Class Cancelled constraints for ' || :NEW.course_id || ' on ' || TO_CHAR(:NEW.booking_date, 'Mon DD'), 0);
        END LOOP;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER check_periodic_dates
BEFORE INSERT ON PeriodicDetails
FOR EACH ROW
BEGIN
    IF :NEW.end_date < TRUNC(SYSDATE) THEN
        RAISE_APPLICATION_ERROR(-20002, 'End date for recurring booking must be today or in the future.');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER audit_bookings
AFTER UPDATE OR DELETE ON Bookings
FOR EACH ROW
DECLARE
    v_action VARCHAR2(20);
BEGIN
    IF DELETING THEN
        v_action := 'DELETE';
    ELSIF UPDATING THEN
        v_action := 'UPDATE';
    END IF;
    
    INSERT INTO Booking_Audit (booking_id, action)
    VALUES (NVL(:OLD.booking_id, :NEW.booking_id), v_action);
END;
/

-- ────────────────────────────────────────────────────────────
-- 6. STORED PROCEDURES, FUNCTIONS, & PACKAGES
-- ────────────────────────────────────────────────────────────

-- Scalar Function: Calculate Total Faculty Hours
CREATE OR REPLACE FUNCTION GET_FACULTY_WORKLOAD(p_faculty_id NUMBER)
RETURN NUMBER
IS
    v_total_hours NUMBER := 0;
BEGIN
    SELECT NVL(SUM((end_time - start_time) * 24), 0)
    INTO v_total_hours
    FROM Bookings
    WHERE faculty_id = p_faculty_id AND status_id != 3;
    
    RETURN v_total_hours;
END;
/

-- Procedure demonstrating Explicit Parameterized Cursors
CREATE OR REPLACE PROCEDURE Generate_Course_Roster(p_course_id IN VARCHAR2)
IS
    CURSOR c_students(course_id_in VARCHAR2) IS
        SELECT u.name, u.email
        FROM Enrollments e
        JOIN Users u ON e.student_id = u.user_id
        WHERE e.course_id = course_id_in;
        
    v_student_rec c_students%ROWTYPE;
    v_count NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- Course Roster for ' || p_course_id || ' ---');
    
    OPEN c_students(p_course_id);
    LOOP
        FETCH c_students INTO v_student_rec;
        EXIT WHEN c_students%NOTFOUND;
        
        DBMS_OUTPUT.PUT_LINE('Student Name: ' || v_student_rec.name || ' | Email: ' || v_student_rec.email);
        v_count := v_count + 1;
    END LOOP;
    CLOSE c_students;
    
    DBMS_OUTPUT.PUT_LINE('Total Enrolled: ' || v_count);
END;
/

-- PL/SQL Package Encapsulation (Specification)
CREATE OR REPLACE PACKAGE Booking_Manager AS
    PROCEDURE Smart_Book(p_user NUMBER, p_room NUMBER, p_date DATE, p_start DATE, p_end DATE);
    PROCEDURE Cancel_Booking(p_booking_id NUMBER, p_user_id NUMBER, p_reason VARCHAR2);
END Booking_Manager;
/

-- PL/SQL Package Encapsulation (Body)
CREATE OR REPLACE PACKAGE BODY Booking_Manager AS
    -- Standard booking procedure implemented inside package
    PROCEDURE Smart_Book(p_user NUMBER, p_room NUMBER, p_date DATE, p_start DATE, p_end DATE)
    IS
        v_conflict NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_conflict
        FROM Bookings
        WHERE room_id      = p_room
          AND booking_date = p_date
          AND status_id   != 3
          AND start_time   < p_end
          AND end_time     > p_start;

        IF v_conflict > 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Conflict detected: room already booked.');
        END IF;

        INSERT INTO Bookings (faculty_id, room_id, booking_date, start_time, end_time, status_id)
        VALUES (p_user, p_room, p_date, p_start, p_end, 1);
        COMMIT;
    END Smart_Book;

    -- Standard cancellation procedure natively handling Audit Triggers
    PROCEDURE Cancel_Booking(p_booking_id NUMBER, p_user_id NUMBER, p_reason VARCHAR2)
    IS
        v_owner NUMBER;
    BEGIN
        SELECT faculty_id INTO v_owner FROM Bookings WHERE booking_id = p_booking_id;
        
        IF v_owner != p_user_id THEN
            RAISE_APPLICATION_ERROR(-20003, 'Unauthorized cancellation attempt.');
        END IF;
        
        UPDATE Bookings SET status_id = 3 WHERE booking_id = p_booking_id;
        INSERT INTO Cancellations (booking_id, cancelled_by, reason) 
        VALUES (p_booking_id, p_user_id, NVL(p_reason, 'Cancelled via PL/SQL Manager'));
        COMMIT;
    END Cancel_Booking;
END Booking_Manager;
/

-- ────────────────────────────────────────────────────────────
-- 7. DEFAULT SEED DATA
-- ────────────────────────────────────────────────────────────
INSERT ALL
    INTO Roles (role_id, role_name) VALUES (1, 'Admin')
    INTO Roles (role_id, role_name) VALUES (2, 'Faculty')
    INTO Roles (role_id, role_name) VALUES (3, 'Student')
    INTO BookingStatuses (status_id, status_name) VALUES (1, 'Confirmed')
    INTO BookingStatuses (status_id, status_name) VALUES (2, 'Pending')
    INTO BookingStatuses (status_id, status_name) VALUES (3, 'Cancelled')
    INTO BookingTypes (type_id, type_name) VALUES (1, 'One-time')
    INTO BookingTypes (type_id, type_name) VALUES (2, 'Recurring')
    INTO DaysOfWeek (day_id, day_name) VALUES (1, 'Sunday')
    INTO DaysOfWeek (day_id, day_name) VALUES (2, 'Monday')
    INTO DaysOfWeek (day_id, day_name) VALUES (3, 'Tuesday')
    INTO DaysOfWeek (day_id, day_name) VALUES (4, 'Wednesday')
    INTO DaysOfWeek (day_id, day_name) VALUES (5, 'Thursday')
    INTO DaysOfWeek (day_id, day_name) VALUES (6, 'Friday')
    INTO DaysOfWeek (day_id, day_name) VALUES (7, 'Saturday')
    INTO NotifTypes (notif_type_id, type_name) VALUES (1, 'Booking Confirmation')
    INTO NotifTypes (notif_type_id, type_name) VALUES (2, 'Cancellation Alert')
    INTO Semesters (semester_id, name, start_date, end_date)
         VALUES (1, 'Semester 1 2025', DATE '2025-01-01', DATE '2025-05-31')
SELECT * FROM dual;

INSERT INTO Departments (name) VALUES ('Computer Science');
INSERT INTO Departments (name) VALUES ('Mathematics');
INSERT INTO Departments (name) VALUES ('Physics');

INSERT INTO Classrooms (building, room_number, capacity, has_projector, has_ac) VALUES ('AB1', '101', 60, 1, 1);
INSERT INTO Classrooms (building, room_number, capacity, has_projector, has_ac) VALUES ('AB1', '102', 40, 1, 1);
INSERT INTO Classrooms (building, room_number, capacity, has_projector, has_ac) VALUES ('AB2', '301', 120, 1, 1);
INSERT INTO Classrooms (building, room_number, capacity, has_projector, has_ac) VALUES ('AB5', 'LH1', 200, 1, 1);
INSERT INTO Classrooms (building, room_number, capacity, has_projector, has_ac) VALUES ('IC', 'Lab A', 30, 0, 1);

INSERT INTO Courses (course_id, title, dept_id, credits) VALUES ('ICT3101', 'Computer Networks', 1, 4);
INSERT INTO Courses (course_id, title, dept_id, credits) VALUES ('ICT3102', 'Embedded Systems', 1, 4);
INSERT INTO Courses (course_id, title, dept_id, credits) VALUES ('MAT2101', 'Engineering Maths', 2, 3);
INSERT INTO Courses (course_id, title, dept_id, credits) VALUES ('DBS202',  'Database Systems', 1, 3);

-- Test Credentials Profiles (For easy login)
INSERT INTO Users (name, email, role_id, password, role) VALUES ('Admin User', 'admin@manipal.edu', 1, 'admin', 'ADMIN');
INSERT INTO Users (name, email, role_id, password, role) VALUES ('Dr. Arnab', 'arnab@manipal.edu', 2, 'password', 'FACULTY');
INSERT INTO Users (name, email, role_id, password, role) VALUES ('Prof. Sarah', 'sarah@manipal.edu', 2, 'password', 'FACULTY');
INSERT INTO Users (name, email, role_id, password, role) VALUES ('Student Test', 'student@manipal.edu', 3, 'password', 'STUDENT');

-- Bulk Faculty Generation (200 Faculty)
BEGIN
  FOR i IN 1..20 LOOP
    INSERT INTO Users (name, email, role_id, password, role) 
    VALUES ('Faculty ' || i, 'faculty' || i || '@manipal.edu', 2, 'password', 'FACULTY');
  END LOOP;
END;
/

-- Bulk Student Generation (150 Students)
BEGIN
  FOR i IN 1..150 LOOP
    INSERT INTO Users (name, email, role_id, password, role) 
    VALUES ('Student ' || i, 'student' || i || '@manipal.edu', 3, 'password', 'STUDENT');
  END LOOP;
END;
/

-- Mass Randomized Student Enrollments
BEGIN
  FOR curr_student IN (SELECT user_id FROM Users WHERE role_id = 3 AND email LIKE 'student%@manipal.edu') LOOP
    -- Every generated student gets Database Systems automatically
    INSERT INTO Enrollments (student_id, course_id, semester_id) VALUES (curr_student.user_id, 'DBS202', 1);
    
    -- Even ID students get Embedded Systems
    IF MOD(curr_student.user_id, 2) = 0 THEN
      INSERT INTO Enrollments (student_id, course_id, semester_id) VALUES (curr_student.user_id, 'ICT3102', 1);
    END IF;
    
    -- Every 3rd student gets Calculus
    IF MOD(curr_student.user_id, 3) = 0 THEN
      INSERT INTO Enrollments (student_id, course_id, semester_id) VALUES (curr_student.user_id, 'MAT2101', 1);
    END IF;
  END LOOP;
END;
/


COMMIT;

SET SERVEROUTPUT ON;
EXEC Generate_Course_Roster('DBS202');

SELECT name, GET_FACULTY_WORKLOAD(2) AS total_hours_teaching
FROM Users
WHERE role = 'FACULTY';


SELECT table_name FROM user_tables ORDER BY table_name;

SELECT * FROM BookingDetails; 
SELECT * FROM RoomUsage; 

-- Booking for AB1/101 on 2025-06-01 from 09:00-10:00 already exists
-- Attempt overlapping booking:
INSERT INTO Bookings(faculty_id,room_id,booking_date,start_time,end_time,status_id)
VALUES(7, 5, DATE '2025-06-01',
       TO_DATE('2025-06-01 11:30','YYYY-MM-DD HH24:MI'),
       TO_DATE('2025-06-01 12:30','YYYY-MM-DD HH24:MI'), 1);
-- Result: ORA-20001: Room already booked for that time slot.


-- After INSERT into Bookings for course DBS202:
SELECT COUNT(*) FROM Notifications;  -- increases by (1 + enrolled student count)

UPDATE Bookings SET status_id = 3 WHERE booking_id = 1;


Select * from Notifications;

SELECT table_name 
FROM user_tables 
WHERE table_name IN (
    'BOOKING_AUDIT', 'NOTIFICATIONS', 'CANCELLATIONS', 
    'PERIODICDETAILS', 'ENROLLMENTS', 'BOOKINGS', 
    'CLASSROOMS', 'COURSES', 'USERS', 'DEPARTMENTS', 
    'SEMESTERS', 'ROLES', 'BOOKINGTYPES', 'BOOKINGSTATUSES', 
    'NOTIFTYPES', 'DAYSOFWEEK'
)
ORDER BY table_name;
