const path = require('path');
const express = require("express");
const cors = require("cors");
const oracledb = require("oracledb");

const app = express();
app.use(cors());
app.use(express.json());

// Oracle DB config
const dbConfig = {
  user: "system",
  password: "system",
  connectString: "localhost:1521/XE",
  externalAuth: false
};

async function checkConn() {
  let c;
  try {
    c = await oracledb.getConnection(dbConfig);
    console.log("✅ Oracle Connection Successful!");
    
    // --- AUTO-PATCH MISSING TABLES ---
    const patches = [
      `CREATE TABLE BookingTypes (type_id NUMBER PRIMARY KEY, type_name VARCHAR2(50) NOT NULL)`,
      `CREATE TABLE DaysOfWeek (day_id NUMBER PRIMARY KEY, day_name VARCHAR2(10) NOT NULL)`,
      `CREATE TABLE PeriodicDetails (periodic_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id NUMBER NOT NULL REFERENCES Bookings(booking_id) ON DELETE CASCADE, day_id NUMBER NOT NULL REFERENCES DaysOfWeek(day_id), end_date DATE NOT NULL)`,
      `CREATE TABLE Cancellations (cancel_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id NUMBER NOT NULL REFERENCES Bookings(booking_id), cancelled_by NUMBER, cancelled_date DATE DEFAULT SYSDATE, reason VARCHAR2(200))`,
      `INSERT INTO BookingTypes (type_id, type_name) VALUES (1, 'One-time')`,
      `INSERT INTO BookingTypes (type_id, type_name) VALUES (2, 'Recurring')`,
      `INSERT INTO DaysOfWeek (day_id, day_name) VALUES (1, 'Sunday')`,
      `INSERT INTO DaysOfWeek (day_id, day_name) VALUES (2, 'Monday')`,
      `INSERT INTO DaysOfWeek (day_id, day_name) VALUES (3, 'Tuesday')`,
      `INSERT INTO DaysOfWeek (day_id, day_name) VALUES (4, 'Wednesday')`,
      `INSERT INTO DaysOfWeek (day_id, day_name) VALUES (5, 'Thursday')`,
      `INSERT INTO DaysOfWeek (day_id, day_name) VALUES (6, 'Friday')`,
      `INSERT INTO DaysOfWeek (day_id, day_name) VALUES (7, 'Saturday')`
    ];
    
    for(let sql of patches) {
      try { await c.execute(sql); await c.commit(); } catch(e) { } // Ignore if already exists
    }
    console.log("✅ Schema Verification Complete!");

  } catch (e) {
    console.error("❌ ORACLE CONNECTION FAILED:", e.message);
  } finally {
    if(c) await c.close();
  }
}
checkConn();

// ─────────────────────────────────────────
// GET /rooms — List all classrooms
// ─────────────────────────────────────────
app.get("/rooms", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(
      `SELECT room_id, building, room_number, capacity, has_projector, has_ac 
       FROM Classrooms ORDER BY room_number`,
      [], { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    res.json(result.rows);
  } catch (err) { res.status(500).json({ error: err.message });
  } finally { if (conn) await conn.close(); }
});

// ─────────────────────────────────────────
// POST /book — Book a room
// ─────────────────────────────────────────
app.post("/book", async (req, res) => {
  const { faculty_id, room_id, course_id, date, start, end, type_id, end_date } = req.body;
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(
      `INSERT INTO Bookings (faculty_id, room_id, course_id, booking_type_id, booking_date, start_time, end_time, status_id)
       VALUES (:f_id, :r_id, :c_id, :t_id, TO_DATE(:b_date, 'YYYY-MM-DD'), 
               TO_DATE(:b_date || ' ' || :s, 'YYYY-MM-DD HH24:MI'), 
               TO_DATE(:b_date || ' ' || :e, 'YYYY-MM-DD HH24:MI'), 1)
       RETURNING booking_id INTO :id`,
      {
        f_id: faculty_id, r_id: room_id, c_id: course_id || null, t_id: type_id || 1, 
        b_date: date, s: start, e: end, id: { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }
      }
    );

    const newBookingId = result.outBinds.id[0];

    // Recurring Setup
    if (type_id == 2 && end_date) {
      const dayId = new Date(date).getDay() + 1; 
      await conn.execute(
        `INSERT INTO PeriodicDetails (booking_id, day_id, end_date)
         VALUES (:b_id, :d_id, TO_DATE(:e_date, 'YYYY-MM-DD'))`,
        { b_id: newBookingId, d_id: dayId, e_date: end_date }
      );
    }
    await conn.commit();
    res.send("Booking successful!");
  } catch (err) { res.status(500).send(err.message);
  } finally { if (conn) await conn.close(); }
});

// ─────────────────────────────────────────
// POST /cancel — Cancel a booking
// ─────────────────────────────────────────
app.post("/cancel", async (req, res) => {
  const { booking_id, user_id, reason } = req.body;
  if (!booking_id || !user_id) return res.status(400).send("Booking ID & User ID required.");
  
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const check = await conn.execute(`SELECT faculty_id FROM Bookings WHERE booking_id = :b_id`, { b_id: booking_id }, { outFormat: oracledb.OUT_FORMAT_OBJECT });
    if (check.rows.length === 0) return res.status(404).send("Booking not found.");
    if (check.rows[0].FACULTY_ID != user_id) return res.status(403).send("🚫 Unauthorized: You can only void your own bookings.");

    await conn.execute(`UPDATE Bookings SET status_id = 3 WHERE booking_id = :b_id`, { b_id: booking_id }, { autoCommit: false });
    await conn.execute(`INSERT INTO Cancellations (booking_id, cancelled_by, reason) VALUES (:b_id, :b_user, :b_rsn)`,
      { b_id: booking_id, b_user: user_id, b_rsn: reason || "Voided via Portal" }, { autoCommit: true });
    res.send("Booking voided.");
  } catch (err) { res.status(500).send(err.message);
  } finally { if (conn) await conn.close(); }
});

// ─────────────────────────────────────────
// POST /login
// ─────────────────────────────────────────
app.post("/login", async (req, res) => {
  const { email, password } = req.body;
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(
      `SELECT user_id, name, role FROM Users WHERE email = :email AND password = :password`,
      { email, password }, { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    if (result.rows.length > 0) res.json(result.rows[0]);
    else res.status(401).send("Invalid credentials.");
  } catch (err) { res.status(500).send(err.message);
  } finally { if (conn) await conn.close(); }
});

// ─────────────────────────────────────────
// GET /timetable — True Recurring Projection
// ─────────────────────────────────────────
app.get("/timetable", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(
      `SELECT b.booking_id, u.name, b.course_id, c.room_number, t.type_name,
              b.booking_date,
              TO_CHAR(b.start_time, 'HH24:MI') AS start_time,
              TO_CHAR(b.end_time,   'HH24:MI') AS end_time,
              p.day_id, p.end_date as periodic_end
       FROM Bookings b
       JOIN Users u ON b.faculty_id = u.user_id
       JOIN Classrooms c ON b.room_id = c.room_id
       LEFT JOIN BookingTypes t ON b.booking_type_id = t.type_id
       LEFT JOIN PeriodicDetails p ON b.booking_id = p.booking_id
       WHERE b.status_id != 3`,
      [], { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    
    // Project natively from JS Dates 
    let projectedTimetable = [];
    for(let row of result.rows) {
       let clone = {...row};
       projectedTimetable.push(clone);
       
       if(row.TYPE_NAME === 'Recurring' && row.PERIODIC_END) {
          if(row.BOOKING_DATE instanceof Date && row.PERIODIC_END instanceof Date) {
              let curr = new Date(row.BOOKING_DATE.getTime());
              let end = new Date(row.PERIODIC_END.getTime());
              
              curr.setDate(curr.getDate() + 7); // Start one week out
              
              let iterations = 0;
              while(curr <= end && iterations < 100) {
                  let newClone = {...row};
                  newClone.BOOKING_DATE = new Date(curr.getTime());
                  newClone.TYPE_NAME = 'Recurring (Projected)';
                  projectedTimetable.push(newClone);
                  curr.setDate(curr.getDate() + 7);
                  iterations++;
              }
          }
       }
    }
    
    // Safe memory sort
    projectedTimetable.sort((a,b) => {
       const da = a.BOOKING_DATE instanceof Date ? a.BOOKING_DATE.getTime() : 0;
       const db = b.BOOKING_DATE instanceof Date ? b.BOOKING_DATE.getTime() : 0;
       return da - db;
    });
    
    res.json(projectedTimetable);
  } catch (err) { 
    console.error("Timetable backend execution error: ", err);
    res.status(500).json({ error: err.message });
  } finally { if (conn) await conn.close(); }
});

// ─────────────────────────────────────────
// NEW STUDENT ENDPOINTS
// ─────────────────────────────────────────
app.get("/student/courses/:id", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(`
      SELECT c.course_id, c.title, c.dept_id, c.credits,
      CASE WHEN e.student_id IS NOT NULL THEN 1 ELSE 0 END AS is_enrolled
      FROM Courses c
      LEFT JOIN Enrollments e ON c.course_id = e.course_id AND e.student_id = :id
    `, {id: req.params.id}, {outFormat: oracledb.OUT_FORMAT_OBJECT});
    res.json(result.rows);
  } catch (err) { res.status(500).json({ error: err.message }); }
  finally { if(conn) await conn.close(); }
});

app.post("/student/enroll", async (req, res) => {
  const { student_id, course_id, semester_id } = req.body;
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const check = await conn.execute(`SELECT * FROM Enrollments WHERE student_id=:s AND course_id=:c`, {s:student_id, c:course_id});
    if(check.rows.length > 0) return res.status(400).send("Already enrolled in this course.");
    
    await conn.execute(`INSERT INTO Enrollments (student_id, course_id, semester_id) VALUES (:s, :c, :sem)`, 
                       {s: student_id, c: course_id, sem: semester_id || 1}, {autoCommit: true});
    res.send("Enrolled successfully in the course catalog.");
  } catch (err) { res.status(500).send(err.message); }
  finally { if(conn) await conn.close(); }
});

app.get("/student/timetable/:id", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(`
      SELECT b.booking_id, u.name, c.room_number, b.course_id, t.type_name,
              b.booking_date,
              TO_CHAR(b.start_time, 'HH24:MI') AS start_time,
              TO_CHAR(b.end_time,   'HH24:MI') AS end_time
       FROM Bookings b
       JOIN Users u ON b.faculty_id = u.user_id
       JOIN Classrooms c ON b.room_id = c.room_id
       LEFT JOIN BookingTypes t ON b.booking_type_id = t.type_id
       JOIN Enrollments e ON b.course_id = e.course_id
       WHERE b.status_id != 3 AND e.student_id = :id
       ORDER BY b.booking_date, b.start_time
    `, {id: req.params.id}, {outFormat: oracledb.OUT_FORMAT_OBJECT});
    res.json(result.rows);
  } catch(err) { res.status(500).json({error:err.message}); }
  finally { if(conn) await conn.close(); }
});

// ─────────────────────────────────────────
// NEW ADMIN ENDPOINTS
// ─────────────────────────────────────────
app.get("/admin/stats", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const bookings = await conn.execute(`SELECT COUNT(*) AS c FROM Bookings`, [], {outFormat: oracledb.OUT_FORMAT_OBJECT});
    const cancellations = await conn.execute(`SELECT COUNT(*) AS c FROM Cancellations`, [], {outFormat: oracledb.OUT_FORMAT_OBJECT});
    const rooms = await conn.execute(`SELECT COUNT(*) AS c FROM Classrooms`, [], {outFormat: oracledb.OUT_FORMAT_OBJECT});
    res.json({
      TOTAL_BOOKINGS: bookings.rows[0].C || 0,
      TOTAL_CANCELLATIONS: cancellations.rows[0].C || 0,
      TOTAL_ROOMS: rooms.rows[0].C || 0
    });
  } catch (err) { res.status(500).json({ error: err.message }); }
  finally { if(conn) await conn.close(); }
});

app.get("/admin/logs", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(`
      SELECT c.cancel_id AS id, c.booking_id, u.name AS actor_name, c.reason AS detail, c.cancelled_date AS log_date
      FROM Cancellations c 
      LEFT JOIN Users u ON c.cancelled_by = u.user_id
      ORDER BY c.cancelled_date DESC
    `, [], {outFormat: oracledb.OUT_FORMAT_OBJECT});
    res.json(result.rows);
  } catch (err) { res.status(500).json({ error: err.message }); }
  finally { if(conn) await conn.close(); }
});

app.get("/admin/courses-stats", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const query = `
      SELECT 
          c.course_id, 
          c.title,
          (SELECT COUNT(student_id) FROM Enrollments WHERE course_id = c.course_id) AS student_count,
          (SELECT LISTAGG(name, ', ') WITHIN GROUP (ORDER BY name) 
           FROM (SELECT DISTINCT u.name FROM Bookings b JOIN Users u ON b.faculty_id = u.user_id WHERE b.course_id = c.course_id AND b.status_id != 3)) AS faculty_names,
          (SELECT LISTAGG(room_number, ', ') WITHIN GROUP (ORDER BY room_number) 
           FROM (SELECT DISTINCT cl.room_number FROM Bookings b JOIN Classrooms cl ON b.room_id = cl.room_id WHERE b.course_id = c.course_id AND b.status_id != 3)) AS room_numbers
      FROM Courses c
      ORDER BY c.title
    `;
    const result = await conn.execute(query, [], {outFormat: oracledb.OUT_FORMAT_OBJECT});
    res.json(result.rows);
  } catch(err) { res.status(500).json({ error: err.message }); }
  finally { if(conn) await conn.close(); }
});

// ─────────────────────────────────────────
// Misc Global Endpoints
// ─────────────────────────────────────────
app.get("/courses", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(`SELECT course_id, title FROM Courses ORDER BY title`, [], { outFormat: oracledb.OUT_FORMAT_OBJECT });
    res.json(result.rows);
  } catch (err) { res.status(500).json({ error: err.message });
  } finally { if (conn) await conn.close(); }
});

app.get("/notifications/:id", async (req, res) => {
  let conn;
  try {
    conn = await oracledb.getConnection(dbConfig);
    const result = await conn.execute(
      `SELECT notif_id, user_id, message, is_read, created_at FROM Notifications WHERE user_id = :id ORDER BY created_at DESC`,
      { id: req.params.id }, { outFormat: oracledb.OUT_FORMAT_OBJECT }
    );
    res.json(result.rows);
  } catch (err) { res.status(500).json({ error: err.message });
  } finally { if (conn) await conn.close(); }
});

// ─────────────────────────────────────────
// Express static 
// ─────────────────────────────────────────
app.use(express.static(__dirname));
app.get("/", (req, res) => res.sendFile(path.join(__dirname, "index.html")));

app.listen(3000, () => console.log("Server running on http://localhost:3000"));